version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 5000:5000
    volumes:
      - ./api/:/api
    environment:
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_started

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - 8080:8080

  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
      - 6379:6379
